project:
  type: website
  output-dir: docs

website:
  title: "Meteo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - favorite.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



